---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Labeler"

on:
  workflow_dispatch:
  pull_request_target:
    branches: ["main"]

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-24.04
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Generate Token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        id: app-token
        with:
          app-id: "${{ secrets.APP_ID }}"
          private-key: "${{ secrets.PRIVATE_KEY }}"

      - name: Labeler
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 #v5.0.0
        with:
          repo-token: "${{ steps.app-token.outputs.token }}"
          configuration-path: .github/labeler.yaml
